name: Lint app code
on: [push]
jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run lint command
        run: swiftlint lint
